<a href="https://colab.research.google.com/github/AlexNedyalkov/Linear-Algebra-Python/blob/master/lntro_to_Matrices_Linear_Algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np


---
# 1 Intro to matrices
---


In [3]:
# square vs. rectangular
S = np.random.randn(5,5)
R = np.random.randn(5,2) # 5 rows, 2 columns
print(R)

[[ 1.09919129e+00 -2.38293170e+00]
 [ 7.75979311e-01  4.58954454e-01]
 [ 1.75291533e-01  6.90525252e-01]
 [ 7.94006216e-01  5.98748641e-01]
 [ 1.74032436e-03 -1.57864980e+00]]


###If a matrix is mirrored around the diagonal it is called symmetric matrix. Only square matrices can be symmetric. 

###Symmetric:        A = A.transpose()

###Skew-symmetric:   A = -A.transpose()

In [9]:
# identity
I = np.eye(3)
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [10]:
# zeros
Z = np.zeros((4,4))
print(Z)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [11]:
# diagonal
D = np.diag([ 1, 2, 3, 5, 2 ])
print(D)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 5 0]
 [0 0 0 0 2]]


###For upper triangular matrices all the elements below the diagonal must zeo. For lower rectangular matrices all the elements above the diagonal must be zero.

In [12]:
# create triangular matrix from full matrices
S = np.random.randn(5,5)
U = np.triu(S)
L = np.tril(S)
print(L)

[[ 0.67771961  0.          0.          0.          0.        ]
 [ 1.12225967 -0.25837398  0.          0.          0.        ]
 [ 1.93455799  0.70508475 -0.55953115  0.          0.        ]
 [ 1.84498846  0.98720115  0.38305783 -0.73002229  0.        ]
 [ 0.16651958 -0.03438629 -0.16018908 -0.95818591 -0.98532125]]


In [13]:
# concatenate matrices (sizes must match!)
A = np.random.randn(4,2)
B = np.random.randn(4,4)
C = np.concatenate((A,B),axis=1)
print(C)

[[-0.29293785  1.17072111  0.12324812  0.02992848 -0.49997312 -0.63830273]
 [-0.7756639  -0.8944732   1.35990339  1.34168252 -1.39606075  0.38673915]
 [ 0.61778387  0.28915741  2.15315367  1.92814331  1.11476888  0.16369447]
 [-2.38978519 -0.12886803 -0.48140692 -1.1668985  -1.0720133   0.45932061]]



---
# 2 Matrix addition and subtraction
---


In [14]:

# create random matrices
A = np.random.randn(5,4)
B = np.random.randn(5,3)
C = np.random.randn(5,4)

# try to add them
A+C



# "shifting" a matrix
l = .3 # lambda
N = 5  # size of square matrix
D = np.random.randn(N,N) # can only shift a square matrix
print(D)

Ds = D + l*np.eye(N)
print(Ds)

[[ 1.27636881  0.35522104 -1.07531468  0.47080849  1.35849981]
 [-0.86470908  0.04451922 -1.18981783  0.206073    0.33245488]
 [ 0.19765453 -0.13393582 -1.31612528  2.27523785 -0.52002094]
 [ 0.27706036  0.11719874 -0.76993177  0.10308921 -0.31377783]
 [-1.77511537  0.21666683  0.36033546 -0.02435009  1.20268701]]
[[ 1.57636881  0.35522104 -1.07531468  0.47080849  1.35849981]
 [-0.86470908  0.34451922 -1.18981783  0.206073    0.33245488]
 [ 0.19765453 -0.13393582 -1.01612528  2.27523785 -0.52002094]
 [ 0.27706036  0.11719874 -0.76993177  0.40308921 -0.31377783]
 [-1.77511537  0.21666683  0.36033546 -0.02435009  1.50268701]]



---
# 3 Matrix-scalar multiplication
---


In [ ]:
# define matrix and scalar
M = np.array([ [1, 2], [2, 5] ])
s = 2

# pre- and post-multiplication is the same:
print( M*s )
print( s*M )


[[ 2  4]
 [ 4 10]]
[[ 2  4]
 [ 4 10]]


# 4 Transpose

In [15]:
M = np.array([ [1,2,3],
               [2,3,4] ])

print(M), print('')
print(M.T), print('') # one transpose
print(M.T.T),print('') # double-transpose returns the original matrix

# can also use the function transpose
print(np.transpose(M))

[[1 2 3]
 [2 3 4]]

[[1 2]
 [2 3]
 [3 4]]

[[1 2 3]
 [2 3 4]]

[[1 2]
 [2 3]
 [3 4]]


In [16]:
# warning! be careful when using complex matrices
C = np.array([ [4+1j , 3 , 2-4j] ])

print(C), print('')
print(C.T), print('')
print(np.transpose(C)), print('')

# Note: In MATLAB, the transpose is the Hermitian transpose; 
#       in Python, you need to call the Hermitian explicitly by first converting from an array into a matrix
print(np.matrix(C).H) # note the sign flips!


[[4.+1.j 3.+0.j 2.-4.j]]

[[4.+1.j]
 [3.+0.j]
 [2.-4.j]]

[[4.+1.j]
 [3.+0.j]
 [2.-4.j]]

[[4.-1.j]
 [3.-0.j]
 [2.+4.j]]



---
# 5 Diagonal and trace
---
The diagonal elements of a covariance matrix contain contains the variance of each variable. As a function diagonalization takes a matrix as input and returns a vector.

__Trace of a matrix is the sum of all the diagonal elements.__

In [17]:

M = np.round( 5*np.random.randn(4,4) )

# extract the diagonals
d = np.diag(M)

# notice the two ways of using the diag function
d = np.diag(M) # input is matrix, output is vector
D = np.diag(d) # input is vector, output is matrix
print(d)
print(D)

# trace as sum of diagonal elements
tr = np.trace(M)
tr2 = sum( np.diag(M) )
print(tr)
print(tr2)

[-6.  2.  4.  4.]
[[-6.  0.  0.  0.]
 [ 0.  2.  0.  0.]
 [ 0.  0.  4.  0.]
 [ 0.  0.  0.  4.]]
4.0
4.0
